# This workflow updates the DS3 documentation mirror at
# https://nex-3.com/ds3/info/.

name: Release DS3

on:
  push:
    tags:
      - 'ds3-[0-9]+.[0-9]+.[0-9]+'
      - 'ds3-[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  update-nex3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.WEBSITE_TOKEN }}
          repository: nex3/nex3.github.io
      - uses: actions/checkout@v6
        with:
          path: Archipelago
      - run: cp -r Archipelago/worlds/dark_souls_3/docs/*.md source/ds3/
      - uses: EndBug/add-and-commit@v9
        with:
          add: source/ds3
          author_name: Nattlebot Robobaum
          author_email: nattlebot@nex-3.com
          message: Update Archipelago docs
